name: Trigger App to Send Mail

on:
  schedule:
    #- cron: '0 6 * * 1-5'   # 06:00 UTC, Monday–Friday
    - cron: '*/5 * * * 1-5'  # mail at Every 5 Min , Monday–Friday
  workflow_dispatch:       # Optional manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API endpoint
        run:
          #curl -s GET "https://903lfiezrf.execute-api.us-east-1.amazonaws.com/prod/journeys?origin=Aalto-yliopisto&destination=Kone-Building&arriveBy=20250911084500"
          curl -s GET ${{ vars.ROUTE_PLANNER_URL }}
