name: Trigger App to Send Mail

on:
  schedule:
    #- cron: '0 3 * * *'  # mail at 6 AM
    - cron: '*/5 * * * *'  # mail at Every 5 Min
  #workflow_dispatch:       # Optional manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API endpoint
        run: |
          curl -X GET "https://j2o21w4is7.execute-api.us-east-1.amazonaws.com/prod/journeys?origin=Aalto-yliopisto&destination=Kone-Building&arriveBy=20250911084500"
